### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by zenspider**
Half is via @phiggins and the other half was me getting frustrated at linux.

### CODE REVIEW

**Comment by phiggins** [comment]
I ended up writing a gem for font selection, btw: https://github.com/phiggins/elefont

**Comment by zenspider** [comment]
http://rathergood.com/elephant/

**Comment by phiggins** [comment]
What the hell did I just watch?

**Comment by zenspider** [comment]
This has drifted. I'm manually applying my commit.

**Pull request closed without merging**
